name: Python Tests and Coverage
on: [push, pull_request]
jobs:
  tests:
    name: CPython ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu, Windows, macOS]
        # https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    env:
      PYTHONWARNDEFAULTENCODING: 1
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        if: matrix.python-version != '3.12'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          #TODO: allow-prereleases will be available as of the next release of setup-python
          # (https://github.com/actions/setup-python/pull/414)
          # then we can drop the if on this step and drop the following step
          #allow-prereleases: true
      - name: Set up Python 3.12.0-alpha.7
        if: matrix.python-version == '3.12'
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.0-alpha.7"
      - name: Install Dependencies
        run: |
          python --version
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      - name: Python Tests (for non-Linux)
        if: matrix.os != 'Ubuntu'
        run: python -m unittest -v
      - name: Python Tests and Coverage (for Linux)
        if: matrix.os == 'Ubuntu'
        run: |
          pip install coverage && \
          coverage run    --rcfile=.coveragerc${{ matrix.python-version }} --branch -m unittest -v && \
          coverage report --rcfile=.coveragerc${{ matrix.python-version }} --show-missing --fail-under=100
